repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.243'
  hooks:
    - id: ruff
      args: ["--fix"]
-   repo: https://github.com/mwouts/jupytext
    rev: v1.14.4
    hooks:
    -   id: jupytext
        args:
          - --pipe
          - black
        files: \.ipynb$
        additional_dependencies:
        - black
-   repo: local
    hooks:
    -   id: clean-notebook
        name: Clean notebook and hide solutions
        entry: python utils/clean_notebook.py
        language: system
        files: \.ipynb$
