repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        additional_dependencies:
        - toml
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/mwouts/jupytext
    rev: v1.14.1
    hooks:
    -   id: jupytext
        args:
          - --pipe
          - black
        files: \.ipynb$
        additional_dependencies:
        - black
-   repo: local
    hooks:
    -   id: clean-notebook
        name: Clean notebook and hide solutions
        entry: python utils/clean_notebook.py
        language: system
        files: \.ipynb$
