[project]
name = "python-tutorial"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
build = { cmd="jupyter-book build book --path-output .", inputs=["book/"], outputs=["_build/"] }
open = { cmd="open _build/html/index.html", depends-on=["build"] }

[environments]
default = ["book", "colab"]

[feature.colab.dependencies]
python = "3.10.12"
numpy = "1.26.4"
scipy = "1.13.1"
matplotlib = "3.7.1"
pandas = "2.1.4"
ipykernel = ">=5.5.6"
nbformat = "5.10.4"

[feature.book.dependencies]
jupyter-book = "*"
jupytext = "*"
