[project]
name = "python-tutorial"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
build = { cmd="jupyter-book build book --path-output .", inputs=["book/"], outputs=["_build/"] }
open = { cmd="open _build/html/index.html", depends-on=["build"] }

[tasks.get-colab-deps]
env = { GH = "https://github.com/googlecolab/backend-info/raw/main" }
cmd = "curl -OL $GH/os-info.txt; curl -OL $GH/pip-freeze.txt;"
outputs = ["os-info.txt", "pip-freeze.txt"]

[environments]
default = ["book", "colab"]
lint = ["lint"]

[feature.colab.dependencies]
python = "==3.11.12"
numpy = "==2.0.2"
scipy = "==1.15"
matplotlib = "==3.10.0"
pandas = "==2.2.2"
ipykernel = "==6.17.1"
nbformat = "==5.10.4"
ipywidgets = "==7.7.1"

[feature.book.dependencies]
jupyter-book = "*"
jupytext = "*"

[feature.lint.dependencies]
pre-commit = "*"
pre-commit-hooks = "*"
ruff = "*"
mdformat = "*"
mdformat-ruff = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
lint-staged = "pre-commit run"
lint-all = "pre-commit run --all-files"
